### ISSUE TITLE
Red line under the navigation titlebar extends slightly too far to the right.

### ISSUE THREAD

**Issue by cole-rogers** [naro143/hugo-coder-portfolio#4]
For some reason, the red line under the navigation title bar link seems to extend to the right too much.  Occurs both on the Hugo demo (both english and Japanese), and my site.

**Comment by naro143** [comment]
Hello @retiform.
Thank you for report.
I can not confirm this problem.
Please send a screenshot.

**Comment by cole-rogers** [comment]
Here is an example from your hugo example site: https://imgur.com/a/6f6dfoP
Sorry about the blur.

Notice how the red line sticks out more on the right hand side than the left.

**Comment by naro143** [comment]
Hello @retiform.
Thank you for image.
I fixed it.
Please confirm it.

Thank you.

**Comment by cole-rogers** [comment]
It looks like you fixed it!

**Comment by cole-rogers** [comment]
So it appears I was wrong.  The issue is not fixed, but I have some new information. As far as I can tell, the issue only affects Firefox, not Chrome or GNOME Web (I tested it with Quantum not the old firefox). Can you point me to the stuff that creates the red line so I can look into this further?

**Comment by naro143** [comment]
Hello @retiform 
Thank you for report.
Please wait for a while as I will investigate.
Thank you!

**Comment by naro143** [comment]
Hello @retiform.
I fixed it.
Please confirm it.

Thank you.

**Comment by cole-rogers** [comment]
Alright, I think the issue is actually fixed this time, since my site no longer as the issue after I updated it.
